
name: via
description: A modern, type-safe HTTP client library for Dart/Flutter applications.
version: 1.0.0+1
repository: https://github.com/GeceGibi/via

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  very_good_analysis: ^10.0.0
